### ISSUE TITLE
Оценка за контрольную работу №3

### ISSUE THREAD

**Issue by mininaiv** [TheFaser/OrenburgLabs#1]
Оценка 5. Не поняла конечно твой комментарий "not full correctly, but ok" над методом get_age

**Comment by TheFaser** [comment]
> Оценка 5. Не поняла конечно твой комментарий "not full correctly, but ok" над методом get_age

Комментарий "not full correctly, but ok" означает, что этот метод несовсем правильно высчитывает возраст. Он отнимает год рождения и текущий год, но не учитывает день рождения.
Подумал, что такая реализация в рамках контрольной работы подойдёт, поэтому написал "but ok"
